version: '3.5'

services:
  ui_build:
    build: ../
    container_name: 'ui_build'
    volumes:
      - dist:/usr/src/app/dist
 
  ui_ws:
    build: ../../ws
    container_name: 'ui_ws'
    ports:
      - 8080:8080

  ui_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'ui_web'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    dist: