version: '3.5'

services:
  backend:
    build: ../../eurochem_advanced
    container_name: 'backend'
    ports:
        - 5000:5000
    command: 
        "python3 app.py"
    volumes:
        - ../../eurochem_advanced:/usr/src/eurochem_advanced

  ui_ws:
    build: ../../ws
    container_name: 'ui_ws'
    ports:
        - 8080:8080
    command:
        "python3 -u main.py --ee http://backend:5000"

  ui_build:
    build: ../
    container_name: "ui_build"
    volumes:
        - dist_ui:/usr/src/app/dist
  
  ui_site:
    build: ../../ui-site
    container_name: "ui_site"
    volumes:
        - dist_ui_site:/usr/src/app/public

  ui_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'ui_web'
    restart: unless-stopped
    volumes:
      - dist_ui:/usr/share/ui:ro
      - dist_ui_site:/usr/share/ui-site:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    dist_ui:
    dist_ui_site: