version: '3.5'

services:
  backend:
    build: ../../eurochem_advanced
    image: backend
    container_name: backend
    ports:
      - 5000:5000
    command: python3 app.py
    volumes:
      - .:/usr/src/eurochem_advanced

  ui_ws:
    build: ../../ws
    image: ui_ws
    container_name: 'ui_ws'
    ports:
        - 8080:8080
    command:
        "python3 -u main.py --ee http://backend:5000"

  ui_build:
    build: ../
    image: ui_build
    container_name: 'ui_build'
    volumes:
      - dist:/usr/src/app/dist 
  
  ui_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'ui_web'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    dist: